### ISSUE TITLE
parse_json suffers the "Unicode Bug"

### ISSUE THREAD

**Issue by Grinnz** [benkasminbullock/JSON-Parse#46]
According to https://metacpan.org/pod/JSON::Parse#Handling-of-Unicode, this parsing function has an inappropriate dependency on the internal state of the Perl strings it receives. This is known as the "unicode bug" (slightly different but related to the [one discussed in perlunicode](https://perldoc.perl.org/perlunicode#The-%22Unicode-Bug%22)).

The "marked as Unicode characters" feature the documentation describes does not exist in Perl; the UTF8 bit of a string only indicates which form of storage the string is used internally, and aside from the interpreter's internals (and by extension your XS code) it has no bearing on the string's logical contents - the codepoints it will appear to contain to perl string operators such as eq or regexes - whether it is intended to represent characters, bytes, or otherwise.

A string that contains only codepoints in the ISO-8859-1 range can be upgraded or downgraded at any time, sometimes by Perl operations transparently as you note, without changing the logical contents of the string. This can be verified by the output of `sprintf '%vX', $str` being identical before and after an upgrade or downgrade.

So it is generally inappropriate to ask the user of an API to manage the internal state of strings which Perl does not guarantee to be stable. The function should define whether it takes decoded characters or UTF-8 bytes, and it is the user's error if they fail to provide the desired logical contents, because Perl will not alter that.

I'm not sure what is the right option of these two choices; generally, having APIs accept and return decoded characters is the most user-friendly, but JSON is a special case where users most commonly will have bytes and this is why most modules promote decode_json for general use over from_json.

Unfortunately there is no way to fix this without a breaking change for users who were relying on this broken heuristic, as [DBD::mysql found](https://github.com/perl5-dbi/DBD-mysql/issues/117) and led to the fork [DBD::MariaDB](https://metacpan.org/pod/DBD::MariaDB) to consistently interpret parameter strings.

Here is a test that would verify that strings are being interpreted consistently (assuming you were to document it to accept decoded characters, otherwise apply `utf8::encode $input` first):

```
use strict;
use warnings;
use JSON::Parse 'parse_json';
use Test::More;

my @chars = map { chr } 

my $input = qq{"\N{U+B5}"};
my $str = "\N{U+B5}";

utf8::downgrade $input;
is parse_json($input), $str, 'read latin1 character (downgraded)';
utf8::upgrade $input;
is parse_json($input), $str, 'read latin1 character (upgraded)';

done_testing;
```

For extensive prior discussions on this issue in other modules:

https://github.com/perl5-dbi/DBD-mysql/issues/197
https://github.com/tobyink/p5-html-html5-parser/pull/3

I don't know much about the XS side of this other than: the SvPVutf8 and SvPVbyte macros are recommended to consistently interpret Perl string contents as characters encoded to UTF-8 or as bytes respectively, they will transparently work the same for upgraded and downgraded strings.

**Comment by benkasminbullock** [comment]
On Tue, 5 Jan 2021 at 08:48, Dan Book <notifications@github.com> wrote:

> For extensive prior discussions on this issue in other modules:
>
> perl5-dbi/DBD-mysql#197
> <https://github.com/perl5-dbi/DBD-mysql/issues/197>
>
Thank you for the message. Since this issue may take some time and thought
to resolve, preliminarily I've read your bug report and the above
discussion. Regarding the MySQL discussion, a lot of the concerns expressed
there seem valid but not relevant in this case.

There is a lot of discussion there concerned about the difference between
binary and non-binary text data. However, JSON is a text format, and not
only that it is a Unicode-only format. Since its creation, JSON::Parse has
advertised itself as a "UTF-8 only" JSON parsing module. At the time of its
creation in 2011, the only other possibility was BOM-distinguished UTF-16
JSON, which did not exist in practice, and nobody ever used it, so I
decided not to bother supporting it. Since then the JSON standard itself
has admitted this and actually changed to say "UTF-8 only":

https://tools.ietf.org/html/rfc8259#section-8.1

"JSON text exchanged between systems that are not part of a closed
   ecosystem MUST be encoded using UTF-8 [RFC3629
<https://tools.ietf.org/html/rfc3629>]."


So unlike the MySQL driver, we do not need to worry about messing up
someone's binary data or someone's Shift-JIS data or something with our
false presumptions about Unicode. If the input is not valid Unicode UTF-8
bytes, we reject it.

(Incidentally the Go language does actually try to send binary data through
JSON which is something of a fiasco in my opinion but it does work as long
as you are just doing round-trips back to Go. It turns its non-Unicode-safe
bytes like `[]byte` into base 64 encoding, regardless of what text is in
them. I have thought that might be a good idea to do that in some kind of
Go-extension module.)

Anyway, getting back to the subject, independent of what Perl thinks, any
bytes which travel through JSON::Parse (or JSON::Create) are valid UTF-8.
Apart from the defunct json-whitespace.c, there are only two places in the
code where it even looks at SvUTF8 things:

```
[ben@mikan] {09:43 16} json3 507 $ grep -n SvUTF8 *.c *.xs
json-entry-points.c:51:    parser->unicode = SvUTF8 (json) ? 1 : 0;
json-perl.c:562: SvUTF8_on (string);
```

Other than that it does not care at all what Perl thinks about the bytes,
it doesn't use any of the Perl Unicode validations for example. It just
churns through the user bytes checking they are all UTF-8 encoded by
itself. It does not set the `force_unicode` flag unless the input has high
bytes within it, so the single `SvUTF8_on` above doesn't get called unless
there are non-ASCII bytes in the output buffer, and it does not set the
`unicode` flag unless the input is marked as SvUTF8 by Perl, as seen above.
So the module is rather careful about doing the thing that you say it
shouldn't be doing.

I'll read the other discussion too and let you know what I think later on.

**Comment by Grinnz** [comment]
You seem to be talking about the bytes in Perl's internals, which unfortunately is different from consistency at the Perl API level that I am talking about. For XS code you in fact must care what Perl thinks about the bytes in any access, to be consistent with Perl operations like eq. The test I presented demonstrates the sort of consistency a Perl user should expect from strings. Let me know if there's anything else I can elaborate on to help.

**Comment by benkasminbullock** [comment]
Thanks for responding and for providing the coded example using `utf8::downgrade`.
```
my $input = qq{"\N{U+B5}"};
my $str = "\N{U+B5}";
utf8::downgrade $input;
is parse_json($input), $str, 'read latin1 character (downgraded)';
utf8::upgrade $input;
is parse_json($input), $str, 'read latin1 character (upgraded)';
```
This is in fact a problem with my module as you say. Similarly when I started it it didn't process the UTF-16 with BOM bytes. Luckily they removed that from the JSON standard. But calling `utf8::downgrade` on a string of two-byte Unicode which can be converted into a single byte is deliberately throwing a spanner in the works, I can't see cases where this happens in practice.

<blockquote>
A string that contains only codepoints in the ISO-8859-1 range can be upgraded or downgraded at any time, sometimes by Perl operations transparently as you note, without changing the logical contents of the string. 
</blockquote>
So far I haven't received any bug reports from users about Perl upgrading and downgrading their two-byte UTF-8 into single bytes, causing my module to crash. 

To be thorough, I tried to find a place in the Perl source code where it downgrades. It's done by the function `sv_utf8_downgrade`. Looking at the installed Perl 5.32.0 on my system, I have one example in sv.c where it downgrades the record separator `$/` on line 8565, and I've found three functions in mathoms.c and one in sv.c where the comment at the top of the function says "don't use this function, use `<something>` instead". There are also two in pp.c where it downgrades in the `crypt` function and where it is processing for octal and hex, and there is one more in `universal.c` which I think is what you're actually calling with the above utf8::downgrade. Then there is `S_to_byte_substr` in `regexec.c`. That seems to be related to the internal processing in regex matching. Perhaps a capture from a regex like `$1` would provide an example of where my module goes wrong in practice, something like the module [Text::JSON::Nibble](https://metacpan.org/pod/Text::JSON::Nibble) might give a string of Unicode which is unmarked as utf8 and is downgraded, so let's say that was sent to `valid_json` in my module, it would cause the problem? There is also a case in `pp_pack.c` related to unpacking.

I'm not saying that this cannot happen at all, but under what circumstances does it actually occur?

I have to go out now, but I will look at the tobyink module about HTML later on, I'm sure that discussion is very interesting. Thank you.

**Comment by Grinnz** [comment]
The point is rather not "when can it occur" but that it *can* occur and that the Perl interpreter provides no assurance that it will not, nor is it designed to keep the storage interface stable, nor is it useful to require every user to understand how the internals of Perl strings work in order to correctly use CPAN. (That it's somewhat required in order to work with filenames in core functions notwithstanding 😬)

> But calling utf8::downgrade on a string of two-byte Unicode which can be converted into a single byte is deliberately throwing a spanner in the works

This is not what downgrade does, from the perspective of Perl code. It's important in this discussion to separate the logical contents of strings as they are used in Perl operations, from the bytes that the interpreter stores to keep track of the contents. The logical contents are in practice a function of those bytes and the UTF8 bit in tandem, hence the suggested macros that always take both into account.

If you have a string which `utf8::downgrade` converts into a single byte internally, it was already logically a single character string. `length` and `sprintf '%vX'` will both report one character, before and after downgrading. The same regexes will match (assuming you've enabled consistent unicode rules with the unicode_strings feature). It does not matter to any correctly-written Perl code which format it is stored in. It matters to the XS code, since XS has to deal at the level of this abstraction. So it's the job of such XS code to keep it from mattering to the Perl code written for it.

If it helps imagine where this can be problematic, the problem you note above can also happen in reverse: a string that logically contains UTF-8 bytes can get upgraded, resulting in the same string of UTF-8 bytes, but the internal bytes are the double-encoded form of those text characters. With correct interpretation of the UTF8 bit, it will still be treated as the same bytes regardless.

**Comment by benkasminbullock** [comment]
@Grinnz - you need to read what I have written and respond to it. This was the first time this happened, a long conversation with you where you cherry picked bits of what I said and wrote long responses to me without addressing the bulk of what I'd said. Now I have the same experience with you on the Perl Porter mailing list. It is a waste of my time writing responses to people who don't bother to read them.
